add cache m2 to travis-ci. delete openjdk13,openjdk14,openjdk-ea because java 1.6 cannot be used on such jdks. delete openjdk11 because CalendarValidatorTest, DateValidatorTest, TimeValidatorTest will fail on jdk11 as:
```
[ERROR] Failures:
[ERROR]   CalendarValidatorTest.testDateTimeStyle:197 validate(A) default
[ERROR]   CalendarValidatorTest.testFormat:215 default expected:<31/12/[]05> but was:<31/12/[20]05>
[ERROR]   CurrencyValidatorTest.testIntegerValid:142 US negative expected:<-1234.00> but was:<null>
[ERROR]   CurrencyValidatorTest.testInvalid:121 US wrong negative
[ERROR]   CurrencyValidatorTest.testValid:93 US negative expected:<-1234.56> but was:<null>
[ERROR]   DateValidatorTest.testDateValidatorMethods:69 validate(A) both expected:<Sat Dec 31 00:00:00 CST 2005> but was:<null>
[ERROR]   TimeValidatorTest.testTimeZone:224 pattern result
[ERROR] Errors:
[ERROR]   CalendarValidatorTest.testCalendarValidatorMethods:70 NullPointer
```