Re-run Maven using the -X (--debug) switch to get info for ...
Error:  Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.24.0:check (default-cli) on project commons-validator: PMD 7.4.0 has found 1 violation. For more details see: /home/runner/work/commons-validator/commons-validator/target/pmd.xml -> [Help 1]